name: "Build Frontegg iOS SDK"

on:
  push:
    branches-ignore:
      - master
env:
  CI: true
  LANG: en_US.UTF-8

concurrency:
  group: ci-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
