name: iOS starter workflow

on:
  push:
    ignore-branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          scheme: ${{ 'demo' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          cd demo
          xcodebuild build-for-testing -scheme "$scheme" -project demo.xcodeproj -destination "platform=$platform,name=iPhone 14 Pro"
      - name: Test
        env:
          scheme: ${{ 'demo' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          cd demo
          xcodebuild test-without-building -scheme "$scheme" -project demo.xcodeproj -destination "platform=$platform,name=iPhone 14 Pro"
