name: iOS starter workflow

on:
  push:
    ignore-branches: [ "master" ]

jobs:
  build-and-test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} #os switching
    strategy:
      fail-fast: false #if 'true' then one failed job cancels all jobs remaining
      matrix:
        xcode: [ '14.2.0', '13.4.1' ]
        macos: [ 'macos-latest' ]
        scheme: [ 'demo' ]
        command: [ 'test' ]
        platform: [ 'iOS' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: mxcl/xcodebuild@v1.9.2
        with:
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
          action: ${{ matrix.command }}
          working-directory: "demo"
          code-coverage: true
          verbosity: xcpretty
          upload-logs: always
#      - name: Build
#        env:
#          scheme: ${{ 'demo' }}
#          platform: ${{ 'iOS Simulator' }}
#        run: |
#          xcodebuild build-for-testing -scheme "$scheme" -project demo/demo.xcodeproj -destination "platform=$platform,name=iPhone 14 Pro"
#      - name: Test
#        env:
#          scheme: ${{ 'demo' }}
#          platform: ${{ 'iOS Simulator' }}
#        run: |
#          cd demo
#          xcodebuild test-without-building -scheme "$scheme" -project demo.xcodeproj -destination "platform=$platform,name=iPhone 14 Pro"
