name: "onPush( Build & Test )"

on:
  push:
    ignore-branches: [ "master" ]

jobs:
  build-and-test:
    name: "Test on  iOS Simulator (xcode: 14.2.0, macos: latest)"
    runs-on: 'macos-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mikehardy/buildcache-action@v2
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: '14.2.0'
      - name: Clone Mock Server
        uses: actions/checkout@v3
        with:
          repository: frontegg/frontegg-mock-server
          ssh-key: ${{ secrets.MOCK_SERVER_SSH_KEY }}
          ref: "master"
          path: mocker
      - name: Install  Mock Server
        working-directory: mocker
        run: |
          yarn install
          cd packages/mobile-mocker
          (yarn start&)
      - name: Double-check macOS version (macos-latest)
        run: sw_vers
      - name: Double-check Xcode.app selected
        run: xcode-select --print-path
      - name: Check xcodebuild version
        run: xcodebuild -project demo/demo.xcodeproj -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -project demo/demo.xcodeproj -showsdks
      - name: Show buildable schemes
        run: xcodebuild -project demo/demo.xcodeproj -list
      - name: Show eligible build destinations for the "demo"
        run: xcodebuild -project demo/demo.xcodeproj -showdestinations -scheme "demo"
      - name: Test
        working-directory: "demo"
        run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ test -scheme "demo" -project "demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -resultBundlePath "test.xcresult" -enableCodeCoverage "YES"
      - name: "Upload test results"
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'test.xcresult'
          path: demo/test.xcresult
