name: "onPush( Build & Test )"

on:
  push:
    ignore-branches: [ "master" ]

jobs:
  build-and-test:
    name: "Test on  iOS Simulator (xcode: 14.2.0, macos: latest)"
    runs-on: 'macos-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Mock Server
        uses: actions/checkout@v3
        with:
          repository: frontegg/frontegg-mock-server
          ssh-key: ${{ secrets.MOCK_SERVER_SSH_KEY }}
          ref: "master"
          path: mocker
      - name: Run Mock Server
        working-directory: mocker
        run: |
          yarn install
          cd packages/mobile-mocker
          (yarn start&)
      - name: Register Ngrok
        uses: actions/github-script@v6
        with:
          script: |
            const { default: modifyEntitlements } = require('.github/scripts/modify-entitlements.js')
            await modifyEntitlements({github, fetch})
      - name: Double-check macOS version (macos-latest)
        run: sw_vers
      - name: Double-check Xcode.app selected
        run: xcode-select --print-path
      - name: Check xcodebuild version
        run: xcodebuild -project demo/demo.xcodeproj -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -project demo/demo.xcodeproj -showsdks
      - name: Show buildable schemes
        run: xcodebuild -project demo/demo.xcodeproj -list
      - name: Show eligible build destinations for the "demo"
        run: xcodebuild -project demo/demo.xcodeproj -showdestinations -scheme "demo"
      - name: Build for Testing
        run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ build-for-testing -scheme "demo" -project "demo/demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -enableCodeCoverage "YES"
      - name: Test without Building
        run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ test-without-building -scheme "demo" -project "demo/demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -resultBundlePath "TestResults" -enableCodeCoverage "YES"
      - name: "Parse Test XCResults"
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: TestResults.xcresult
